# Nixpacks configuration for Railway deployment
# https://nixpacks.com/docs/configuration/file

[phases.setup]
aptPkgs = [
  "libgl1-mesa-glx",
  "libglib2.0-0", 
  "libsndfile1",
  "ffmpeg",
  "portaudio19-dev"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
